### PR TITLE
Seq.iteri, exists, contains, forall, trypick, pick, tryfind, find, re…

### PR DESCRIPTION
**Pull request by liboz**
…duce, last, trylast

cleanup for Seq.iter, fold

Also moves the functions in the seq.fsi file to be alphabetical

### CODE REVIEW

**Comment by manofstick** [comment]
Over half way there on the list of functions (54/99) but I think we've definitely broken the back of the problem. Nice Work!

I've come down with a cold, so not sure if this will mean I'll get extra time (if I'm just a little sick) or no time (if I'm fully sick!) We'll see how we go.

**Comment by liboz** [comment]
Hope you feel better and it's the first situation instead of the latter.

**Comment by manofstick** [comment]
@liboz 

OK; I should have checked this a little better, but I have fixed them up now.

So the API is a bit confusing for foreach; I could have added another layer in there to remove the confusion, but considering performance is what we are after I didn't... Anyway the confusing thing is that the ProcessNext that it requests ignores the result. So you can return true or false and nothing happens. This then ties into the other confusion, which was that stopping the steam using the pipeline halts after the current step (as no other processing is happening further up). So you don't need to (and it is an error to) process one more item after you desired result.

Anyway, I have patched them all up. Hopefully got them right...

**Comment by liboz** [comment]
Whoops, sorry for that.

I noticed that your latest set of changes uses a function to get the values from the folder. Is that better than using the property? I feel like that is likely to be a cost in performance.

Also, if we just use this new inline `foreach` do we still need to expose `toComposer` in the public surface. Maybe we can just expose `foreach` in the SeqComposer module, which is probably much less confusing to deal with?

**Comment by manofstick** [comment]
No function involved in getting data from the folder. It is an embedded struct which is better in the ways. First is data locality for cache, second is accessibility (no extra pointer involved), third is garbage as no extra object.

Anything inlined still needs to remain in the public surface.

**Comment by liboz** [comment]
Surely `fun folded -> folded.Value` is a function? I agree that using the struct is better, but what is the difference (and do we care) between your implementation and say. I'm asking because I think we have to allocate the local variable anyways, but you also have to allocate the function I describe above.

```
let fold = 
    let folded = source |> foreach (whatever)

    folded.Value
```

**Comment by manofstick** [comment]
Oh sorry I didn't know what you were referring to :-)

The fsharp compiler inlined the |> so it's all good, and I think reads nicer.

**Pull request merged**
