### PR TITLE
fix bug where unfold did not respect the Halted state on Result

### PR DESCRIPTION
**Pull request by liboz**

### CODE REVIEW

**Comment by manofstick** [comment]
Good catch. I think I went through all the ForEachs the other day looking for these cases. Could you Trevor to make sure that I did?

**Comment by liboz** [comment]
I did a quick look through the other Foreach-es and the other movenext-s and they all seem to be okay except maybe the append which doesn't have a halt, but that one seems special anyways.

**Comment by manofstick** [comment]
Append is special, and will become more special when I blend in the concat logic (and probably collect as well)

It is one of the places where we are absolutely killing it for performance improvement (the other is init(Infinite))

I think it is probably those two functions that cemented in my head that the Seq implementation was so awful, but I didn't actually Hunt down the actually cause so it started me on this mission to improve Seq in general. And hey, I'm glad I did, because I'm actually quite chuffed that, if you allow inline, we can match the Nessos stream library whilst remaining compatible with IEnumerable and matching all the idiosyncrasies of the existing Seq impregnation (oops autocorrect again! Implementation!)

(And we still have our next card so up or sleeve! Oh look, I might as well tell you, but I was hoping to try it out first and I was waiting for the full implementation before I prototyped it, but hey you're in this as much as me now so I'll tell you my plan! Ok, so now we have a two phased construction progress via the factory objects, so we can insert extra instructions into the stream defining how the construction of the final objects should proceed. So what I'm thinking, at least as a first instruction, would be to create with buffer (Auto correct had that as butter, which is kind of apt as we're showing it over the layers!) Now this is obvious not free, as we would have to provide a new ProcessNext function which took an array<> rather than a single element, so it is a bit of work, but i don't think it would be significantly more. Obviously this could MoveNext on the original source past it's natural end point before halting, but that would be a user choice. And then the second instruction we could insert into the stream should be to do the processing on that array in parallel... But that is getting way ahead of where we are! Anyway, hope this excites!)

**Comment by manofstick** [comment]
Oh, and Nessos Streams does use inline, so it's not like they could end up with an extra boost. I went and had a bit of a look through the code and, I guess unsurprisingly, it is not particularly different from what we have ended up with, although they are doing everything with straight lambda functions rather than custom abstract functions.

I didn't hang around enough to grok their method of collapsing everything into a final value and how they handled cancellation, as they seem to define their main streaming call as just 'a->unit, but maybe they just carry around the equivalent of the "movenext" result in the same manner as the cancellation.

Anyway I don't think there was anything really there that we aren't doing in a sufficient manner.

**Pull request merged**
