### PR TITLE
seq.comparewith

### PR DESCRIPTION
**Pull request by liboz**

### CODE REVIEW

**Comment by liboz** [comment]
Hmm... maybe it's just me but I found this to be slower than before...

Edit: Just kidding, I found a small improvement (50ms or so) for both 32 and 64 bit when in chain of `seq` functions. with the following test function:

```
let data = seq {
        let mutable x = 0L
        while x < 10000000L do
            yield x
            x <- x + 1L }

data
        |> Seq.map id
        |> Seq.filter (fun n -> n = n)
        |> Seq.map id
        |> Seq.compareWith (fun i j -> int(i - j)) data
```

That's what I get for trying to benchmark when playing a game...

**Comment by manofstick** [comment]
...it should also give an improvement if the data was an array or a list...

**Comment by manofstick** [comment]
Oh, and you also have the sequences around the wrong way if you want to see what you should be achieving as a performance improvement - i.e. changing your code to:

```
let composerData = 
    data
    |> Seq.map id
    |> Seq.filter (fun n -> n = n)
    |> Seq.map id

data |> Seq.compareWith (fun i j -> int(i - j)) composerData
```

gives it a big kick. i.e. this was the same concern when I removed the second case of map2.

Hmmm... we could check to see if we are the composer and then just switch the sources around, and just multiple the end result by -1 if we have...

**Comment by liboz** [comment]
Yea... and maybe in general for the functions that involve 2+ sources, we should favor the last one for piping reasons?

**Comment by manofstick** [comment]
Hmmm...

I'm in two minds about this. Piping in regards to multi stream seqs is confusing to begin with, as what you imagine as the first input is really the second it means that the compare with returns is values around the wrong way to the intuitive feel. The same problem is with Append where the "streamed" one comes after. This caught me out the first time I used it.

Anyway what I usually do now to avoid confusion is have a fun line, create a tuple and the use the double pipe operator.

I.e.

```
|> Seq.xxx
|> fun data -> data, data2
||> seq.compareWith comparer
```

Anyway, what I'm getting at, in a round about way, is that my personal usage benefits from the first argument being a composer, whereas I can understand why the second would be.

So I don't think we can win, unless we make both.

**Pull request merged**
