### PR TITLE
sumby, average, averageby, max, maxby, min, minby

### PR DESCRIPTION
**Pull request by liboz**

### CODE REVIEW

**Comment by manofstick** [comment]
Good work!

I'm thinking that maybe we add a toComposer method (which would then have to become part of the public surface, but we are already polluting that space) and then we just remove the old enumerable access, that would simplify the implementations, removing the duplication.

I think this makes access to non composer sequences slightly slower, but not greatly, and that is probably the much lesser case...

Thoughts?

**Comment by manofstick** [comment]
... And actually it would make non-composer types faster if the underlying object is an array or a list as well have better iteration...

**Comment by liboz** [comment]
Do you mean something like

`let toComposer source = source |> seqFactory (SeqComposer.IdentityFactory ())`

If so, it seems like an okay idea. I wonder how much that could hurt the speed on a non-list/array.

**Comment by manofstick** [comment]
Exactly.

And then we have singleton Identitys (toe specific of course) just so we're not creating any extra rubbish than we need.

And then in the ForEach the identity gets ripped off when we combine with the consumer, as per existing logic.

Can you give it a burl?

**Comment by liboz** [comment]
Sure. I'll try it out.

**Pull request merged**
