### PR TITLE
[WIP] inline foreach seq functions

### PR DESCRIPTION
**Pull request by cloudRoutine**

### CODE REVIEW

**Comment by cloudRoutine** [comment]
@manofstick should `tryPick`, `tryItem`, & `tryFind` be `inline` as well?

**Comment by cloudRoutine** [comment]
@manofstick like with the `map` family of functions that take 2 or more sequences among their parameters, I wasn't sure how to adapt the `foreach` functions that use 2 or more sequences either (`exists2`, `iteri2`, `fold2`, `compareWith`, etc). If you could give me an example for map2 or more and the 2 or more seq foreach functions I could do the rest myself and we'll be almost finished 😀

**Comment by manofstick** [comment]
@cloudRoutine 

Here is an example of map2 (untested)...

    [<CompiledName("Map2")>]
    let inline map2<'First,'Second,'U> (map:'First->'Second->'U) (source1:ISeq<'First>) (source2:ISeq<'Second>) : ISeq<'U> =
        source1 |> compose { new SeqFactory<'First,'U>() with
            member __.Create<'V> outOfBand pipeIdx next =
                upcast { new ConsumerChainedWithStateAndCleanup<'First,'V, IEnumerator<'Second>>(Upcast.iCompletionChain next, (source2.GetEnumerator ())) with
                    member self.ProcessNext input =
                        if self.Value.MoveNext () then
                            TailCall.avoid (next.ProcessNext (map input self.Value.Current))
                        else
                            outOfBand.StopFurtherProcessing pipeIdx
                            false

                    override self.OnDispose () = ()
                    override self.OnComplete _ =
                        self.Value.Dispose ()  } }

At the Seq side it would just get `toComposer` for both the inputs.

Got no more time now; sorry.

I'm thinking of adding an alternative to `GetEnumerator()` / `MoveNext` / `Current` which would get something like `GetFastEnumerator` and have a function like `TryGetNext` which would be a single call that takes a byref and returns a bool to cut down on the roundtripping...

**Comment by cloudRoutine** [comment]
@manofstick i've zapped the mapfactories,  shifted the foreach folders, and elevated the composers.
Should all of the composers containing `foreach` folders be marked `inline` or not?
Is there anything else I can do to help move this forward?

**Comment by manofstick** [comment]
@cloudRoutine 

Hey dude, great work. I've merged it over, and I'll give it a quick check over now. Hopefully on the w/end I'll get more of a chance.

**Comment by manofstick** [comment]
@cloudRoutine 

OK; had a bit of bashing; can have a look at checkin history to see what. Anyway, as far as making things inline:

1. Anything that takes a function (like `iteri`, not like `tryHead`)
2. Anything that has the equality constraint (the compiler creates a comparer for it)

...I'll have a look more when I get some time...

Gotta run!

**Pull request merged**
