### PR TITLE
Seq.scan

### PR DESCRIPTION
**Pull request by liboz**
Not sure if there's an easier way. Having the initial value as the first element is a bit awkward with our set up.

### CODE REVIEW

**Comment by manofstick** [comment]
I know so little git commands that I don't know how to merge this :-O!

Anyway, sorry about that, could you patch up and I'll pull it in before I stuff up the main branch again...

(Had a nasty-ish Tail issue that I had to resolve. I've "fixed" it - it had to do with who halted the pipeline - before of after the Take (there is an example in the check-in) - and my solution involved basically enumerating the pipeline and using the index to determine where we were. But I numbered things from the tail as 1, and 0 as no halt. But 0 kind of implies the head node halts (i.e. runs out of MoveNext), and so the indexing should be from there. Which would make the logic in OnComplete of Tail make more sense, but I then need a more automatic way of dealing out an id from the consumers with a foreach. Anyway, I probably will flip it around when I have hashed out all those details. But not now.)

**Comment by liboz** [comment]
I rebased my commit to after yours, so I think it should be good now.

**Comment by liboz** [comment]
Looking at it again... Does your new implementation even halt anymore? When is `result.Halted` ever set to `0`?

**Comment by manofstick** [comment]
Well it should get halted, 0 is the stream was halted (I.e. it was halted by the natural run to the end of the data source, I.e. MoveNext had returned false and we then are complete, so OnComplete is called with the 0th index). The confusion, as it currently stands, is that my indexing then jumps to the end of the stream and counts up and it gets closer to the start. I.e. in the order of the factory's creation.

So what I will do is give the index to the factory on creation and it will then use that to create the underlying object. But I had already headed down the current path beforei thought about it enough.

Anyway, I'll fix that up tonight hopefully.

As said indexing is bad, and will need to be revisited

**Comment by manofstick** [comment]
OK; Had another attempt at fixing the Take issue. I think it is more intuitive now; although I don't like a mutation that I have added to the factory object; but I didn't really want to have to create another object each time.

The alternative to all of this is just to remove it all, and not implement `Take` within the Composer framework; but it is a bit of a cop out? Hmmm... Fair bit of complexity to handle that case... I'll dwell on it...

**Comment by liboz** [comment]
Okay, this implementation makes a lot more sense logically.

If you wanted to remove the mutability, you can maybe do something like this where we basically have a secondary (internal) constructor that takes `pipelineDepth` as a variable and increments it by 1 when composed. I did `choose` because it was the closest.

```
                type [<AbstractClass>] SeqComponentFactory<'T,'U> () =
                [<DefaultValue>]
                val mutable private pipelineDepth: int

                internal new (pipelineDepth:int) as this = 
                    SeqComponentFactory() then this.pipelineDepth <- pipelineDepth


                abstract Create<'V> : ISeqPipeline -> SeqConsumer<'U,'V> -> SeqConsumer<'T,'V>

                member this.PipelineDepth =
                    this.pipelineDepth

            and ComposedFactory<'T,'U,'V> private (first:SeqComponentFactory<'T,'U>, second:SeqComponentFactory<'U,'V>, pipelineDepth: int) =
                inherit SeqComponentFactory<'T,'V> (pipelineDepth)
                override __.Create<'W> (result:ISeqPipeline) (next:SeqConsumer<'V,'W>) : SeqConsumer<'T,'W> =
                    first.Create result (second.Create result next)

                static member Combine (first:SeqComponentFactory<'T,'U>) (second:SeqComponentFactory<'U,'V>) : SeqComponentFactory<'T,'V> =
                    let nextDepth = first.PipelineDepth + 1
                    let composed = ComposedFactory(first, second, nextDepth)
                    upcast composed

            and ChooseFactory<'T,'U> =
                inherit SeqComponentFactory<'T,'U>
                val filter : 'T->option<'U>
                private new (filter:'T->option<'U>, pipeLineDepth:int) =
                            { inherit SeqComponentFactory<'T,'U> (pipeLineDepth); filter = filter}
                new (filter:'T->option<'U>) = { inherit SeqComponentFactory<'T,'U> (); filter = filter }
                override this.Create<'V> (_result:ISeqPipeline) (next:SeqConsumer<'U,'V>) : SeqConsumer<'T,'V> = upcast Choose (this.filter, next) 

```

**Comment by manofstick** [comment]
But the factory object gets created in exposed Seq functions at which time it is constructed with no knowledge of the pipeline, which only occurs after the Combine is called? So I don't think that solves the problem (only viewing on my phone so might be missing something). Create could be parametized with the pipeline, but that bleeds to much info out for callers to know about...

Hmmm...

**Comment by liboz** [comment]
Well, the `Combine` function on the `ComposedFactory` takes takes 2 factories first and second. The value of second's depth is not relevant.

If first is a `ComposedFactory`, it will have a non-default value for `pipelineDepth` and then we can use that to increment by 1 and our result from `Combine` will have a deeper `pipelineDepth`. If first just a user created factory (i.e. Choose), then the `pipelineDepth` is its default value, which can again be incremented by 1 for the new `ComposedFactory`, which will have a non-default value for `pipelineDepth` again.

**Comment by manofstick** [comment]
But the pipeline depth on the Combine is only used as a placeholder. The actual object is created in the underlying factoriesv where the depth will remain as 1...

Ie. TailFactory's Create creates the Tail object which is the one that actually needs the Pipeline depth. It doesn't have access to the Combines Pipelines depth...? Anyway as said, I'm only on my phone. I'll have a play at home tonight.

**Comment by manofstick** [comment]
...I did some cleaning up of it which has been pushed...

Anyway, starting to build some performance figures from different sources. The [gist is here](https://gist.github.com/manofstick/b685a5acfe99f39f44c9cf06b89d2fe2). Not much done yet - that's all for tonight though...

**Pull request merged**
