### PR TITLE
[WIP] Inline Composers

### PR DESCRIPTION
**Pull request by cloudRoutine**
### Filters/Creators

- [ ] `allPairs`
- [ ] `append`
- [ ] `cache`
- [ ] `cast`
- [x] `choose`
- [ ] `chunkBySize`
- [ ] `collect`
- [ ] `concat`
- [ ] `countBy`
- [ ] `delay`
- [x] `distinct`
- [x] `distinctBy`
- [ ] `splitInto`
- [x] `except`
- [x] `filter`
- [x] `where`
- [ ] `groupBy`
- [x] `indexed`
- [ ] `init`
- [ ] `initInfinite`
- [x] `map`
- [x] `mapi`
- [ ] `ofArray`
- [ ] `ofList`
- [x] `pairwise`
- [ ] `permute`
- [ ] `readonly`
- [ ] `replicate`
- [ ] `rev`
- [x] `scan`
- [ ] `singleton`
- [ ] `skip`
- [x] `skipWhile`
- [ ] `sort`
- [ ] `sortWith`
- [ ] `sortBy`
- [ ] `sortDescending`
- [ ] `sortByDescending`
- [x] `tail`
- [x] `take`
- [x] `takeWhile`
- [x] `truncate`
- [x] `windowed`
- [ ] `zip`
- [ ] `zip3`

### Consumers

- [ ] `average`
- [ ] `averageBy`
- [ ] `compareWith`
- [ ] `contains`
- [ ] `exists`
- [ ] `exists2`
- [ ] `find`
- [ ] `findIndex`
- [ ] `fold`
- [ ] `fold2`
- [ ] `forall`
- [ ] `forall2`
- [ ] `head`
- [ ] `tryHead`
- [ ] `last`
- [ ] `tryLast`
- [ ] `exactlyOne`
- [ ] `isEmpty`
- [ ] `item`
- [ ] `iter`
- [ ] `iteri`
- [ ] `iter2`
- [ ] `iteri2`
- [ ] `length`
- [ ] `max`
- [ ] `maxBy`
- [ ] `min`
- [ ] `minBy`
- [ ] `nth`
- [ ] `pick`
- [ ] `reduce`
- [ ] `sum`
- [ ] `sumBy`
- [ ] `toArray`
- [ ] `toList`
- [ ] `tryFind`
- [ ] `tryFindIndex`
- [x] `tryItem`
- [ ] `tryPick`

### Filters/Creators
- [ ] `empty`
- [ ] `map2`
- [ ] `map3`
- [ ] `mapi2`
- [ ] `mapFold`
- [ ] `mapFoldBack`
- [ ] `scanBack`
- [ ] `unfold`

### Consumers
- [ ] `findBack`
- [ ] `findIndexBack`
- [ ] `foldBack`
- [ ] `foldBack2`
- [ ] `reduceBack`
- [ ] `tryFindBack`
- [ ] `tryFindIndexBack`

### CODE REVIEW

**Comment by cloudRoutine** [comment]
can you move distinct into the area that consumes the ISeqs? (i.e. there are only a couple of functions there at the moment, but map, filter, mapi and choose you did I think.)

And then the Seq.distinct just becomes a stub that calls that version after the seqFactory? And restore seqFactory to private, and don't inline it.

Rule of thumb of inlining is functions that take functions as input, and as I mentioned in other thread, where we are using HashIdentity (otherwise HashIdentity gives us the generic version, which boxes value types of non-primatives and no custom tuple handling, which can lead to boxing as well.). BUT don't worry about these at the moment, as we'll need to expand the surface area yet again to handle these.

**Comment by cloudRoutine** [comment]
I saw that and figured it'd be cleaner to use another type than nesting `Value<'a,'b>` in the simplevalue component, but I'll do it that way instead

**Comment by manofstick** [comment]
The advantage of the values struct is that the common type can be shared across the multiple usages (I.e. flavours of SeqCompoonent and ForEach usages) without having to add extra types to the surface area.

**Comment by cloudRoutine** [comment]
I'm confused about why this is an issue, aren't all of the `SeqComponent` types  overriding `OnComplete` from `[<AbstractClass>] Consumer`?

**Comment by manofstick** [comment]
It is a bit confusing, and I should probably have some better naming around there, but there are two OnComplete methods that are different. The first is on the interface and that is used to chain all the methods together, as well as managing exceptions. This makes it easier to implement as every consumer doesn't need to do that correctly. The second OnComplete/onDispose is on the class and that is just the provided implantation.

Now as a micro optimisation the Simple versions don't call the underlying class methods. This micro optimisation was just added to enhance performance in the case of very small (or empty) enumerations, it just removed a virtual call at each level. This was in the same class of micro optimizations that I was playing around with by passing the byref unit.

Anyway they are kind of excessive, but they are in a core library so I don't mind being a bit excessive as they *should* be used all over and (so maybe I'll eventually save enough energy in the world light a room for a few seconds!)

**Comment by cloudRoutine** [comment]
Is this the type I should be implementing?

```fsharp
and [<AbstractClass>] SeqComponentValue<'T,'U,'Value> (next:ICompletionChaining, init) =
    inherit SeqComponent<'T,'U>(next)

    let mutable value : 'Value = init

    member  __.Value with get() = value and set v = value <- v

    interface ICompletionChaining with
        member this.OnComplete (stopTailCall, terminatingIdx) =
            this.OnComplete terminatingIdx
            next.OnComplete (&stopTailCall, terminatingIdx)
        member this.OnDispose stopTailCall  =
            try     this.OnDispose ()
            finally next.OnDispose (&stopTailCall)
```
or should it be this?

```fsharp
and [<AbstractClass>] SeqComponentValue<'T,'U,'Value> (next:ICompletionChaining, init) as self =
    inherit SeqComponent<'T,'U>(next)

    [<DefaultValue>] val mutable Value : 'Value

    do self.Value <- init

    interface ICompletionChaining with
        member this.OnComplete (stopTailCall, terminatingIdx) =
            this.OnComplete terminatingIdx
            next.OnComplete (&stopTailCall, terminatingIdx)
        member this.OnDispose stopTailCall  =
            try     this.OnDispose ()
            finally next.OnDispose (&stopTailCall)                        
```

the problem is trying to implement `skip` with either of them

```fsharp
[<CompiledName "Skip">]
let inline skip (skipCount:int) (source:ISeq<'T>) : ISeq<'T> =
    source |> compose { new SeqFactory<'T,'T>() with
        member __.Create _ _ next =
            upcast {
                new SeqComponentValue<'T,'U,int>(Upcast.iCompletionChaining next,(*count*)0) with

                    override self.ProcessNext (input:'T) : bool =
                        if (*count*) self.Value < skipCount then
                            self.Value <- self.Value + 1
                            false
                        else
                            TailCall.avoid (next.ProcessNext input)

                interface ICompletionChaining with
                    member self.OnComplete (stopTailCall, terminatingIdx) =
                        let self = self :?> SeqComponentValue<'T,'U,int>
                        if (*count*) self.Value < skipCount then
                            let x = skipCount - self.Value
                            invalidOpFmt "{0}\ntried to skip {1} {2} past the end of the seq"
                                [|SR.GetString SR.notEnoughElements; x; (if x=1 then "element" else "elements")|]

                    member this.OnDispose stopTailCall  =
                        try     (this :?> Consumer<_,_>).OnDispose ()
                        finally (Upcast.iCompletionChaining next).OnDispose (&stopTailCall)

                interface ISkipping with
                    member self.Skipping () =
                        let self = self :?> SeqComponentValue<'T,'U,int>
                        if (*count*) self.Value < skipCount then
                            self.Value <- self.Value + 1
                            true
                        else
                            false
            }}
```

leads to 

```
"C:\repos\visualfsharp\build-everything.proj" (default target) (1) ->
"C:\repos\visualfsharp\src\fsharp\FSharp.Core\FSharp.Core.fsproj" (Build target) (2) ->
(CoreCompile target) ->
  C:\repos\visualfsharp\src\fsharp\FSharp.Core\seqcomposer.fs(1138,24): error FS1113: The value 'skip' was marked inline  but its implementation makes use of an internal or private function which is not sufficiently accessible [C:\repos\visu alfsharp\src\fsharp\FSharp.Core\FSharp.Core.fsproj]
  C:\repos\visualfsharp\src\fsharp\FSharp.Core\seqcomposer.fs(1138,24): error FS1113: The value 'skip' was marked inline  but its implementation makes use of an internal or private function which is not sufficiently accessible [C:\repos\visu alfsharp\src\fsharp\FSharp.Core\FSharp.Core.fsproj]
  C:\repos\visualfsharp\src\fsharp\FSharp.Core\seqcomposer.fs(1138,24): error FS1113: The value 'skip' was marked inline  but its implementation makes use of an internal or private function which is not sufficiently accessible [C:\repos\visu alfsharp\src\fsharp\FSharp.Core\FSharp.Core.fsproj]
  C:\repos\visualfsharp\src\fsharp\FSharp.Core\seq.fs(94,37): error FS1114: The value 'Microsoft.FSharp.Collections.Comp oserModule.Seq.skip' was marked inline but was not bound in the optimization environment [C:\repos\visualfsharp\src\fsha rp\FSharp.Core\FSharp.Core.fsproj]
  C:\repos\visualfsharp\src\fsharp\FSharp.Core\seqcomposer.fsi(597,20): error FS1113: The value 'skip' was marked inline  but its implementation makes use of an internal or private function which is not sufficiently accessible [C:\repos\visu alfsharp\src\fsharp\FSharp.Core\FSharp.Core.fsproj]
  C:\repos\visualfsharp\src\fsharp\FSharp.Core\seq.fs(94,37): error FS1116: A value marked as 'inline' has an unexpected  value [C:\repos\visualfsharp\src\fsharp\FSharp.Core\FSharp.Core.fsproj]
  C:\repos\visualfsharp\src\fsharp\FSharp.Core\seq.fs(94,37): error FS1118: Failed to inline the value 'skip' marked 'in line', perhaps because a recursive value was marked 'inline' [C:\repos\visualfsharp\src\fsharp\FSharp.Core\FSharp.Core.f sproj]
```

so I'm not sure if I'm missing something, if I misinterpreted what you wanted me to implement, or if the problem is something else.

**Comment by cloudRoutine** [comment]
@manofstick are the functions like the ones below in the final form they need to be or do they need to be modified further?

```fsharp
[<CompiledName("Iterate")>]
let iter f (source:ISeq<'T>) =
    source
    |> foreach (fun _ ->
        { new Consumer<'T,'T> () with
            override this.ProcessNext value =
                f value
                Unchecked.defaultof<_> (* return value unsed in ForEach context *) })
    |> ignore

[<CompiledName("TryHead")>]
let tryHead (source:ISeq<'T>) =
    source
    |> foreach (fun halt ->
        { new Folder<'T, Option<'T>> (None) with
            override this.ProcessNext value =
                this.Value <- Some value
                halt ()
                Unchecked.defaultof<_> (* return value unsed in ForEach context *) })
    |> fun head -> head.Value
```

if they do could you show me how they need to be restructured so I can adjust the rest?

**Comment by cloudRoutine** [comment]
@manofstick I think I've done everything I can without some review and guidance on how to move forward, sorry I've needed so much hand-holding.

**Comment by manofstick** [comment]
@cloudRoutine

Great effort dude! I don't think I out was to much hand holding; there is weirdness at a number of steps due to optimizations/minimising public surface area as well as the style being somewhat unorthodox (hell I had to fix a compiler bug in order to allow this stuff to compile correctly in some cases so it is oddish!)

Possibly we can alleviate some of this with some comments for the next adventurer (possibly for the reviewers from Microsoft land?) So if you think that any comments world help, now is probably the time to add them as the potholes are probably fresh in your mind.

Anyway I'll make some time over the weekend to review/plot path forward.

Thanks for picking up the flame.

**Comment by manofstick** [comment]
@cloudRoutine 

Merging this, so I can play if needed.

**Pull request merged**
